apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobhunter-backend
  labels:
    app: jobhunter-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: jobhunter.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jobhunter-backend
                port:
                  name: http
